### ISSUE TITLE
Switches: Leon remembers the last choice made, even if killed

### ISSUE THREAD

**Issue by serrq** [svenjacobs/leon#309] opened 2023-10-24 17:36 UTC
Sorry for my English. I hope it makes the meaning. It seems like an assassination. 🤣

![1000094374](https://github.com/svenjacobs/leon/assets/113377431/740b4097-0c9b-4940-bcc1-295fbce1b941)

**Comment by svenjacobs** [comment] 2023-10-24 17:59
Is this a bug report or a feature request? 😉

**Comment by svenjacobs** [comment] 2023-10-24 19:18
I think this is a duplicate of #200 then.

**Comment by svenjacobs** [comment] 2023-10-24 19:51
#200 is not about new toggles. It is actually about remembering the toggle states. So this issue is a duplicate, I will close it 😉

**Closed** 2023-10-24 19:51 UTC
