### ISSUE TITLE
Tiktok not working

### ISSUE THREAD

**Issue by soonfries** [svenjacobs/leon#353] opened 2024-01-07 13:02 UTC
I tried Tiktok today it's not working. The Short-URL is not resolved:

![Screenshot](https://github.com/svenjacobs/leon/assets/32013911/87e60662-b0e6-40f0-b282-be11762845b7)

**Comment by svenjacobs** [comment] 2024-01-07 13:06
Hello @soonfries, this is a duplicate of #77. Please read [this issue](https://github.com/svenjacobs/leon/issues/77) and [this discussion](https://github.com/svenjacobs/leon/discussions/80) to learn why Leon can't unwrap Tiktok short URLs. Thank you!

**Closed by svenjacobs** 2024-01-07 13:06 UTC
Labels: wontfix
