### ISSUE TITLE
[Feature Request] Custom Cleaners

### ISSUE THREAD

**Issue by whizzzkid** [svenjacobs/leon#370] opened 2024-03-08 08:04 UTC
I feel custom cleaners could be really helpful. I was thinking regular expressions for robustness, but it could be simpler for accessibility too. The URL params can be provided as a list which can be selected to be deleted, and saved as a pattern for future.

**Comment by svenjacobs** [comment] 2024-03-09 09:02
Thanks for your feedback. This is a duplicate of #70. Please add further comments there.

**Closed by svenjacobs** 2024-03-09 09:02 UTC
