### ISSUE TITLE
[Feature Request] keep history of urls and save notes against it like a bookmark manager.

### ISSUE THREAD

**Issue by whizzzkid** [svenjacobs/leon#371] opened 2024-03-08 08:06 UTC
When using leon as a URL opener, if it could keep a list of old links (auto-delete after N time) and can be pinned, with an option to have simple notes/tags could be great!

**Comment by svenjacobs** [comment] 2024-03-09 09:04
Thanks for your feedback. This is a duplicate of #201. Please add further comments there.

**Closed by svenjacobs** 2024-03-09 09:04 UTC
