### ISSUE TITLE
Crash when default browser doesn't support Custom Tabs

### ISSUE THREAD

**Issue by serrq** [svenjacobs/leon#422] opened 2024-06-20 11:12 UTC
Android 14
Leon 42 (fdroid)
OnePlus CPH2399

![1000113892](https://github.com/svenjacobs/leon/assets/113377431/3776c3aa-a4a1-49e2-b4e6-daf408463da5)

This crash happen after I pushed on "open URLs in a custom tab..." in settings

**Comment by svenjacobs** [comment] 2024-06-20 11:44
I currently only find version `41` on F-Droid. However I cannot reproduce this crash with `41` from F-Droid or `42` from Play Store. Please clear the app data and try if it helps. If not please provide a crashlog (Android logcat) if possible.

**Comment by svenjacobs** [comment] 2024-06-20 12:19
I installed `42` via Droid-ify. I only used the official F-Droid client before. Still no crash.
Please provide a crashlog or I have no idea what's going on.

**Comment by svenjacobs** [comment] 2024-06-20 12:48
What browser is installed on your device?

**Comment by svenjacobs** [comment] 2024-06-21 06:12
Do you know if any of those browsers support [Custom Tabs](https://developer.chrome.com/docs/android/custom-tabs/)? It is a functionality that browsers must implement to support. Could you maybe as a test install the regular Firefox and see if it still crashes? I assume it has something to do with [this code](https://github.com/svenjacobs/leon/blob/e857a500889da6564b92c3f49f810129e34fa74e/app/src/main/kotlin/com/svenjacobs/app/leon/MainActivity.kt#L95-L111).

**Comment by svenjacobs** [comment] 2024-06-21 06:35
I probably need to add a check if the current default browser even supports Custom Tabs.

**Comment by svenjacobs** [comment] 2024-06-21 06:43
Hm, that's interesting. Maybe having Leon as the default browser means Custom Tabs are not possible.

**Comment by svenjacobs** [comment] 2024-09-21 14:18
@serrq I'm sorry, but I can't reproduce this crash. Even when Leon is set as the default browser and custom tabs are enabled, the app does not crash. Nothing happens when I click "open" because Leon as default browser can't handle custom tabs.

Can you please try with the latest version? Also please install via official F-Droid app, just to be sure.

![Screenshot_20240921_161411](https://github.com/user-attachments/assets/e28adf49-553f-41ba-b40b-40e3d1b85c2f)

**Comment by svenjacobs** [comment] 2024-09-21 15:00
Forget what I said. I can reproduce this crash when restarting Leon. A fix is incoming.

**Closed** 2024-09-21 15:09 UTC
Labels: bug
